export enum kvKeys {
  WATCHED_CHANNELS = 'WATCHED_CHANNELS',
  PLAYER_COUNT_FORWARDING_CHANNEL = 'PLAYER_COUNT_FORWARDING_CHANNEL',
  ANDROID_FORWARDING_CHANNEL = 'ANDROID_FORWARDING_CHANNEL',
  PROCESSED_WORLDS = 'PROCESSED_WORLDS'
}
